"""Explicit registry of dashboard HTTP API routes."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Dict, List, Optional

from core.api import handlers


@dataclass(frozen=True)
class ApiRoute:
    method: str
    path: str
    name: str
    handler: Callable[[Dict[str, object]], Dict[str, object]]
    description: Optional[str] = None
    engine_op: Optional[str] = None
    mcp_tool: Optional[str] = None
    meta: bool = False


_ROUTES: List[ApiRoute] = [
    ApiRoute(
        "GET",
        "/api/gpu/info",
        "gpu.info",
        handlers.gpu_info,
        engine_op="gpu.info",
        mcp_tool="gpu_info",
    ),
    ApiRoute(
        "GET",
        "/api/gpu/topology",
        "gpu.topology",
        handlers.gpu_topology,
        engine_op="gpu.topology",
        mcp_tool="gpu_topology",
    ),
    ApiRoute(
        "GET",
        "/api/gpu/power",
        "gpu.power",
        handlers.gpu_power,
        engine_op="gpu.power",
        mcp_tool="gpu_power",
    ),
    ApiRoute(
        "GET",
        "/api/gpu/bandwidth",
        "gpu.bandwidth",
        handlers.gpu_bandwidth,
        engine_op="gpu.bandwidth",
        mcp_tool="gpu_bandwidth",
    ),
    ApiRoute(
        "GET",
        "/api/system/software",
        "system.software",
        handlers.system_software,
        engine_op="system.software",
        mcp_tool="system_software",
    ),
    ApiRoute(
        "GET",
        "/api/system/dependencies",
        "system.dependencies",
        handlers.system_dependencies,
        engine_op="system.dependencies",
        mcp_tool="system_dependencies",
    ),
    ApiRoute(
        "GET",
        "/api/system/context",
        "system.context",
        handlers.system_context,
        engine_op="system.context",
        mcp_tool="system_context",
    ),
    ApiRoute(
        "GET",
        "/api/system/capabilities",
        "system.capabilities",
        handlers.system_capabilities,
        engine_op="system.capabilities",
        mcp_tool="system_capabilities",
    ),
    ApiRoute(
        "GET",
        "/api/system/clock-lock-check",
        "system.clock_lock_check",
        handlers.system_clock_lock_check,
        engine_op="system.clock_lock_check",
        mcp_tool="clock_lock_check",
    ),
    ApiRoute(
        "POST",
        "/api/cluster/eval-suite",
        "cluster.eval_suite",
        handlers.cluster_eval_suite,
        mcp_tool="cluster_eval_suite",
    ),
    ApiRoute(
        "POST",
        "/api/cluster/common-eval",
        "cluster.common_eval",
        handlers.cluster_common_eval,
        mcp_tool="cluster_common_eval",
    ),
    ApiRoute(
        "POST",
        "/api/cluster/fabric-eval",
        "cluster.fabric_eval",
        handlers.cluster_fabric_eval,
        mcp_tool="cluster_fabric_eval",
    ),
    ApiRoute(
        "POST",
        "/api/cluster/nmx-partition-lab",
        "cluster.nmx_partition_lab",
        handlers.cluster_nmx_partition_lab,
        mcp_tool="cluster_nmx_partition_lab",
    ),
    ApiRoute(
        "POST",
        "/api/cluster/build-canonical-package",
        "cluster.build_canonical_package",
        handlers.cluster_build_canonical_package,
        mcp_tool="cluster_build_canonical_package",
    ),
    ApiRoute(
        "POST",
        "/api/cluster/promote-run",
        "cluster.promote_run",
        handlers.cluster_promote_run,
        mcp_tool="cluster_promote_run",
    ),
    ApiRoute(
        "POST",
        "/api/cluster/validate-field-report",
        "cluster.validate_field_report",
        handlers.cluster_validate_field_report,
        mcp_tool="cluster_validate_field_report",
    ),
    ApiRoute(
        "GET",
        "/api/benchmark/contracts",
        "benchmark.contracts",
        handlers.benchmark_contracts,
        mcp_tool="benchmark_contracts",
        meta=True,
    ),
    ApiRoute(
        "POST",
        "/api/benchmark/contracts/render-run",
        "benchmark.contracts.render_run",
        handlers.benchmark_contracts_render_run,
        mcp_tool="render_benchmark_run",
        meta=True,
    ),
    ApiRoute(
        "GET",
        "/api/benchmark/data",
        "benchmark.data",
        handlers.benchmark_data,
        engine_op="benchmark.data",
        mcp_tool="benchmark_data",
    ),
    ApiRoute(
        "GET",
        "/api/benchmark/overview",
        "benchmark.overview",
        handlers.benchmark_overview,
        engine_op="benchmark.overview",
        mcp_tool="benchmark_overview",
    ),
    ApiRoute(
        "GET",
        "/api/benchmark/history",
        "benchmark.history",
        handlers.benchmark_history,
        engine_op="benchmark.history",
        mcp_tool="benchmark_history",
    ),
    ApiRoute(
        "GET",
        "/api/benchmark/trends",
        "benchmark.trends",
        handlers.benchmark_trends,
        engine_op="benchmark.trends",
        mcp_tool="benchmark_trends",
    ),
    ApiRoute(
        "GET",
        "/api/benchmark/tier1/history",
        "benchmark.tier1_history",
        handlers.benchmark_tier1_history,
        engine_op="benchmark.tier1_history",
    ),
    ApiRoute(
        "GET",
        "/api/benchmark/tier1/trends",
        "benchmark.tier1_trends",
        handlers.benchmark_tier1_trends,
        engine_op="benchmark.tier1_trends",
    ),
    ApiRoute(
        "GET",
        "/api/benchmark/tier1/target-history",
        "benchmark.tier1_target_history",
        handlers.benchmark_tier1_target_history,
        engine_op="benchmark.tier1_target_history",
    ),
    ApiRoute(
        "GET",
        "/api/benchmark/compare",
        "benchmark.compare",
        handlers.benchmark_compare,
        engine_op="benchmark.compare",
        mcp_tool="benchmark_compare",
    ),
    ApiRoute(
        "GET",
        "/api/benchmark/targets",
        "benchmark.targets",
        handlers.benchmark_targets,
        engine_op="benchmark.targets",
        mcp_tool="benchmark_targets",
    ),
    ApiRoute(
        "GET",
        "/api/profile/flame",
        "profile.flame_graph",
        handlers.profile_flame,
        engine_op="profile.flame_graph",
        mcp_tool="profile_flame",
    ),
    ApiRoute(
        "GET",
        "/api/profile/kernels",
        "profile.kernels",
        handlers.profile_kernels,
        engine_op="profile.kernels",
        mcp_tool="profile_kernels",
    ),
    ApiRoute(
        "GET",
        "/api/profile/memory",
        "profile.memory_timeline",
        handlers.profile_memory,
        engine_op="profile.memory_timeline",
        mcp_tool="profile_memory",
    ),
    ApiRoute(
        "GET",
        "/api/profile/hta",
        "profile.hta",
        handlers.profile_hta,
        engine_op="profile.hta",
        mcp_tool="profile_hta",
    ),
    ApiRoute(
        "GET",
        "/api/profile/compile",
        "profile.compile_analysis",
        handlers.profile_compile,
        engine_op="profile.compile_analysis",
        mcp_tool="profile_compile_analysis",
    ),
    ApiRoute(
        "GET",
        "/api/profile/roofline",
        "profile.roofline",
        handlers.profile_roofline,
        engine_op="profile.roofline",
        mcp_tool="profile_roofline",
    ),
    ApiRoute(
        "GET",
        "/api/profile/list",
        "profile.list_profiles",
        handlers.profile_list,
        engine_op="profile.list_profiles",
        mcp_tool="profile_list_profiles",
    ),
    ApiRoute(
        "GET",
        "/api/profile/ncu-summary",
        "profile.ncu_summary",
        handlers.profile_ncu_summary,
        engine_op="profile.ncu_summary",
        mcp_tool="ncu_summary",
    ),
    ApiRoute(
        "GET",
        "/api/profile/compare",
        "profile.compare",
        handlers.profile_compare,
        engine_op="profile.compare",
        mcp_tool="profile_compare",
    ),
    ApiRoute(
        "GET",
        "/api/profile/recommendations",
        "profile.recommendations",
        handlers.profile_recommendations,
        engine_op="profile.recommendations",
    ),
    ApiRoute(
        "GET",
        "/api/ai/status",
        "ai.status",
        handlers.ai_status,
        engine_op="ai.status",
        mcp_tool="ai_status",
    ),
    ApiRoute(
        "POST",
        "/api/ai/ask",
        "ai.ask",
        handlers.ai_ask,
        engine_op="ai.ask",
        mcp_tool="ask",
    ),
    ApiRoute(
        "POST",
        "/api/ai/explain",
        "ai.explain",
        handlers.ai_explain,
        engine_op="ai.explain",
        mcp_tool="explain",
    ),
    ApiRoute(
        "GET",
        "/api/ai/tools",
        "ai.tools",
        handlers.ai_tools,
        meta=True,
    ),
    ApiRoute(
        "POST",
        "/api/ai/execute",
        "ai.execute",
        handlers.ai_execute,
        meta=True,
    ),
    ApiRoute(
        "GET",
        "/api/jobs/status",
        "jobs.status",
        handlers.job_status,
        mcp_tool="job_status",
        meta=True,
    ),
]


def get_routes() -> List[ApiRoute]:
    return list(_ROUTES)


def get_dashboard_mcp_tools() -> List[str]:
    """Return MCP tool names explicitly surfaced by dashboard routes."""
    tools = {route.mcp_tool for route in _ROUTES if route.mcp_tool}
    return sorted(tools)
